### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by delannoyk** [wojteklu/Watchdog#14]
Hi!

Carthage support doesn't seem to be working.

Based on the readme, I added `github "wojteklukaszuk/Watchdog" ~> 1.0.2` to my Cartfile. Here's the result:

```
~/B ❯❯❯ carthage update
*** Fetching Watchdog
No available version for github "wojteklukaszuk/Watchdog" satisfies the requirement: ~> 1.0.2
```

So I removed `~> 1.0.2`, but it seems Carthage tries to build the example project instead of the Framework:

```
~/B ❯❯❯ carthage update
*** Fetching Watchdog
*** Checking out Watchdog at "1.0.1"
*** xcodebuild output can be found in /var/folders/ws/xc68hw2j7kb5l6hqtmz0kh7m0000gn/T/carthage-xcodebuild.AfTOro.log
Project "Example.xcodeproj" has no shared schemes
```

**Comment by wojteklu** [comment]
I updated tags. Everything works now. Thanks!
