### ISSUE TITLE
Credit the original?

### ISSUE THREAD

**Issue by neilpa** [wojteklu/Watchdog#2]
This looks like a port of existing Objective-C code that's floated around for a while. You should probably give credit to the original

https://gist.github.com/jspahrsummers/419266f5231832602bec

There may be other implementations out there to but that's what I found with a quick search.

**Comment by wojteklu** [comment]
Added special credit to @jspahrsummers. Indeed he came up first with this awesome idea.

**Comment by neilpa** [comment]
Thanks!
