### ISSUE TITLE
Duration feature is missing in version 2.0

### ISSUE THREAD

**Issue by puttin** [wojteklu/Watchdog#24]

**Comment by wojteklu** [comment]
In v2.0 duration is always the same as defined threshold, so it was removed.

**Comment by puttin** [comment]
Yes, but the log shows kinds of "Main thread was blocked for 0.3s" which does not indicate exact blocked duration like version 1.x. Actually it may have blocked for 0.5s.

**Comment by tbaranes** [comment]
+1 on this. The log doesn't display only the threshold value, not the time we have been blocked.
