### ISSUE TITLE
The duration display the thresold duration instead of how long the app has been blocked

### ISSUE THREAD

**Issue by tbaranes** [wojteklu/Watchdog#26]
In the v1.x, the duration logs in the console was the duration of how long the main thread has been blocked. Starting with the 2.0, the duration is always displaying the threshold duration.

That's a sad regression, it was a really interesting feature. Do you think to bring it back?

**Comment by puttin** [comment]
#24

**Comment by tbaranes** [comment]
Any news about this? 😞

**Comment by wojteklu** [comment]
Hi Tom. It shouldn't be hard to concat version 1.x and 2.x together. However, using solution from 1.x (based on NSRunLoop) it is not possible to find out the exact code which block the main thread. Also I wouldn't recommend using watchdog in production to find proper time of blocking main thread.
