### ISSUE TITLE
Is it possible to change the timeout time during execution?

### ISSUE THREAD

**Issue by zeh4soft** [wojteklu/Watchdog#47]
Watchdog is very useful, thanks a lot, but I have a problem:
During normal execution of my app, I can set a rather small timeout time, say 0.5 sec. This works fine.
However, I have a number of unit stress tests that use unrealistic large data, just to identify potential bottlenecks. To setup these tests, the main thread is busy more than the timeout time of 0.5 sec.
I could of course increase it, but then I would not catch certain problems.
So, what I would like to do is either to disable Watchdog only during the execution of my test setup, or change its timeout time.
Is this possible?

**Comment by wojteklu** [comment]
@zeh4soft yes, it's possible. Feel free to create PR with this change.
