### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by JaviSoto** [wojteklu/Watchdog#5]
Am I missing something?

I wrote some code in viewDidLoad() of a VC to block the main thread for seconds (just a long loop), and the watchdog won't fire (not printing anything). Am I missing something?

**Comment by zshannon** [comment]
+1

**Comment by wojteklu** [comment]
@JaviSoto `Watchdog` is based on main run loop, which is set up and run by `UIApplication`. Small debugging shows that first view controller's `viewDidLoad` is called before it gets any event in the run loop observer. Maybe main run loop is put in motion after loading the users interface. 

However, `Watchdog` will log excessive blocking on the main thread in every other view controller's `viewDidLoad`. Also it will log any blocking in first view controller `viewDidAppear`.  👮

**Comment by JaviSoto** [comment]
@wojteklukaszuk I added this to a VC other than the main one, so it must be a different issue :-/ I can't get it to work.

**Comment by wojteklu** [comment]
@JaviSoto Could you provide example? I'm really curious what is the problem here. 😊

**Comment by wojteklu** [comment]
@JaviSoto Also don't forget to retain Watchdog somewhere or it will get released when it goes out of scope.
